# Generated by Django 5.2.1 on 2025-06-12 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'managed': True},
        ),
    ]
