# Generated by Django 5.2.1 on 2025-06-12 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_alter_event_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='roombooking',
            options={'managed': True},
        ),
    ]
