# Generated by Django 5.2.1 on 2025-06-15 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_alter_event_options_alter_roombooking_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roombooking',
            options={'managed': False},
        ),
    ]
